### ISSUE TITLE
Support variable replacement inside ANKA_TEMPLATE_UUID and ANKA_TAG_NAME variables 

### ISSUE THREAD

**Issue by arifken** [veertuinc/gitlab-runner#13]
As a developer, in my gitlab-ci.yml file, I would like to use other variables inside my anka variables.

Given the following configuration:
```
variables:
    ANKA_TEMPLATE_UUID: "$DEFAULT_ANKA_TEMPLATE_UUID"
    ANKA_TAG_NAME: "$DEFAULT_ANKA_TAG_NAME"
```

Expected: `ANKA_TEMPLATE_UUID` should contain the same value as the `DEFAULT_ANKA_TEMPLATE_UUID` variable
Actual: `ANKA_TEMPLATE_UUID` contains the string literal `$DEFAULT_ANKA_TEMPLATE_UUID` (not the actual variable)

According to @NorseGaud the running theory is that [this](https://github.com/veertuinc/gitlab-runner/blob/4998cda9cbb15ac55cfbb42076051c9dc144e4cd/executors/anka/executor_anka.go#L61-L84) needs to use `Expand` vs `Get`

**Comment by NorseGaud** [comment]
https://github.com/veertuinc/gitlab-runner/releases/tag/v1.5.0
