### ISSUE TITLE
Support for Next GitLab Runner Token Architecture

### ISSUE THREAD

**Issue by childnode** [veertuinc/gitlab-runner#34]
Next GitLab Runner Token Architecture deprecated the registration token in favor of gitlab auth runner token
https://docs.gitlab.com/ee/architecture/blueprints/runner_tokens/

Last release 1.6.0 mentioned "Merged in 14.10.1 code from gitlab-runner" while upstream is on 16.3?

BTW: Registration token is finally EOL in gitlab 17/18 (https://docs.gitlab.com/ee/update/deprecations.html#registration-tokens-and-server-side-runner-arguments-in-gitlab-runner-register-command) even it is not tomorrow https://about.gitlab.com/upcoming-releases/

**Comment by NorseGaud** [comment]
Hi @childnode, the forked version of gitlab-runner is quite behind on updates. We are working on a custom executor you can plug into the official gitlab-runner but it is still being reviewed by our devs before being made public. We recently bumped to the latest 14.x, but likely won't merge in any later version.

Support for the new tokens will be compatible with the custom executor we release in the coming weeks. Just to be sure though, are you saying that your gitlab instance running 16+ will not work with the current runners we provide at 14.x?

**Comment by NorseGaud** [comment]
This is now available in https://github.com/veertuinc/anka-cloud-gitlab-executor
